### ISSUE TITLE
Examples in the wild

### ISSUE THREAD

**Issue by awrog** [hughbris/grav-theme-solarize#11]
The website https://kaibaumgartner.com is mentioned as ' Example in the wild' 
This website of Kai is not Solarize-based but Agency-based

**Comment by kaihawaii110007** [comment]
Migrated recently from Solarize. It was pretty much the same looking.

**Comment by awrog** [comment]
Indeed, what's missing is Solarize is the possibility to keep the menu fixed at the top.

**Comment by hughbris** [comment]
I haven't monitored Kai's site for changes. I've now removed it from the README. I've asked almost everyone who participates in this repo if they have an example I can link to. Kai was the only one who stepped up.

@awrog If you want to change something in the theme, I won't include it unless it's the same as the source theme, since this is simply a port and I'm not a designer and don't even use this theme ATM. Of course, the license allows you to fork it. I would probably make some derived theme tweaks too if I used it.

I think maybe I added some needed alt text to the original design, but that's about it.
